# pubspec.yaml
name: wislet
description: A new Flutter project for managing personal finances.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  crypto: ^3.0.3
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.6
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^19.4.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.2.4
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: any
  http: ^1.2.1
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.3
  intl: ^0.20.2
  local_auth: ^2.2.0
  mobile_scanner: ^7.0.1
  package_info_plus: ^8.0.0
  path: ^1.9.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  rxdart: ^0.28.0
  sentry_flutter: ^9.6.0
  share_plus: 11.1.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  sqflite: ^2.3.3+1
  supabase_flutter: ^2.10.0
  table_calendar: ^3.2.0
  timezone: ^0.10.0
  uni_links: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
    - assets/
    - assets/fonts/
    - assets/patterns/

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon.png
  min_sdk_android: 21
